//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace NovibetApi.Migrations
//{
//    [DbContext(typeof(ApplicationDbContext))]
//    [Migration("20240813120339_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.7")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("NovibetApi.Models.Country", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("GETUTCDATE()");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("ThreeLetterCode")
//                        .IsRequired()
//                        .HasMaxLength(3)
//                        .HasColumnType("nvarchar(3)");

//                    b.Property<string>("TwoLetterCode")
//                        .IsRequired()
//                        .HasMaxLength(2)
//                        .HasColumnType("nvarchar(2)");

//                    b.HasKey("Id");

//                    b.ToTable("Countries", (string)null);
//                });

//            modelBuilder.Entity("NovibetApi.Models.IPAddress", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CountryId")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("CreatedAt")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("GETUTCDATE()");

//                    b.Property<string>("IP")
//                        .IsRequired()
//                        .HasMaxLength(15)
//                        .HasColumnType("nvarchar(15)");

//                    b.Property<DateTime>("UpdatedAt")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("GETUTCDATE()");

//                    b.HasKey("Id");

//                    b.HasIndex("CountryId");

//                    b.HasIndex("IP")
//                        .IsUnique();

//                    b.ToTable("IPAddresses", (string)null);
//                });

//            modelBuilder.Entity("NovibetApi.Models.IPAddress", b =>
//                {
//                    b.HasOne("NovibetApi.Models.Country", "Country")
//                        .WithMany()
//                        .HasForeignKey("CountryId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.Navigation("Country");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
